"""Add role to Invitation model

Revision ID: 22a2e065ec82
Revises: 2f9d3f9f90c0
Create Date: 2025-10-07 09:42:42.769671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a2e065ec82'
down_revision: Union[str, None] = '2f9d3f9f90c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('role', sa.Enum('WATCH', 'STANDARD', 'POLICE', 'MIDDLE_MANAGER', 'SUPER_ADMIN', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'role')
    # ### end Alembic commands ###
