"""Add trading_restricted_until to User model

Revision ID: 2f9d3f9f90c0
Revises: d339d8abee2f
Create Date: 2025-10-07 08:19:29.216869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9d3f9f90c0'
down_revision: Union[str, None] = 'd339d8abee2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trading_restricted_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trading_restricted_until')
    # ### end Alembic commands ###
