"""Machine-verifiable inventory of externally observable three-site effects.

The inventory distinguishes durable business effects from disposable user-interface
responses.  It is deliberately data rather than prose so a review can detect a new
provider surface that has not received an authority, idempotency, ambiguity, and
readiness decision.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any


EFFECT_INVENTORY_SCHEMA = "three-site-dr-effect-inventory-v1"


def _entry(
    name: str,
    *,
    authority: str,
    provider: str,
    durability: str,
    causation: str,
    destination_identity: str,
    idempotency: str,
    claim: str,
    outcomes: list[str],
    ambiguity_policy: str,
    readiness: str,
    source_files: list[str],
    notes: str,
) -> dict[str, Any]:
    return {
        "ambiguity_policy": ambiguity_policy,
        "authority": authority,
        "causation": causation,
        "claim": claim,
        "destination_identity": destination_identity,
        "durability": durability,
        "idempotency": idempotency,
        "name": name,
        "notes": notes,
        "outcomes": outcomes,
        "provider": provider,
        "readiness": readiness,
        "source_files": sorted(source_files),
    }


def build_three_site_effect_inventory() -> dict[str, Any]:
    effects = [
        _entry(
            "telegram_private_notification_outbox",
            authority="foreign",
            provider="telegram",
            durability="durable_foreign_local_outbox",
            causation="source_type plus immutable source identity",
            destination_identity="recipient user id plus Telegram id snapshot",
            idempotency="telegram_notification_outbox.dedupe_key unique constraint",
            claim="leased foreign-only worker claim",
            outcomes=["sent", "retry_pending", "skipped", "terminal_failed"],
            ambiguity_policy="expired sending claim is terminal/manual-review; never blind retry",
            readiness="non-terminal and exhausted receipt counts",
            source_files=[
                "core/notifications.py",
                "core/services/telegram_notification_outbox_service.py",
                "core/services/user_account_status_service.py",
                "core/services/user_deletion_service.py",
                "api/routers/users.py",
                "api/routers/sync.py",
            ],
            notes="Project membership and other asynchronous private notifications use one row per recipient.",
        ),
        _entry(
            "telegram_offer_publication_and_edit",
            authority="foreign",
            provider="telegram",
            durability="durable_offer_publication_state",
            causation="offer public id, home authority, and offer version",
            destination_identity="channel id and persisted Telegram message id",
            idempotency="offer_publication_states.dedupe_key and gateway idempotency keys",
            claim="foreign publication worker serializes the persisted publication state",
            outcomes=["pending", "sent", "visible", "failed", "disabled", "lagged"],
            ambiguity_policy="unknown send result remains failed/lagged for reconciliation; integration must preserve candidate queue semantics",
            readiness="pending/failed/lagged publication reconciliation counts",
            source_files=[
                "api/routers/offers.py",
                "core/offer_expiry.py",
                "core/services/telegram_offer_channel_service.py",
                "core/services/telegram_offer_publication_service.py",
            ],
            notes="The sibling candidate/telegram-offer-publication-queue owns the final queue implementation; integration must not regress this contract.",
        ),
        _entry(
            "telegram_trade_delivery",
            authority="foreign",
            provider="telegram",
            durability="durable_per_trade_per_recipient_receipt",
            causation="trade_completed event type and trade number",
            destination_identity="recipient user id plus Telegram id at send",
            idempotency="trade_delivery_receipts.dedupe_key unique constraint",
            claim="leased foreign-only receipt claim",
            outcomes=["sent", "retry_pending", "skipped", "not_required", "permanent_failed"],
            ambiguity_policy="expired processing lease is reconciled and never blindly resent",
            readiness="all required trade delivery receipts terminal",
            source_files=[
                "api/routers/trades.py",
                "core/services/trade_telegram_delivery_service.py",
            ],
            notes="One receipt exists per event, trade, recipient, and channel.",
        ),
        _entry(
            "telegram_admin_broadcast",
            authority="foreign",
            provider="telegram",
            durability="durable_per_recipient_receipt",
            causation="telegram_admin_broadcasts row",
            destination_identity="recipient user id plus Telegram id snapshot",
            idempotency="telegram_admin_broadcast_receipts.dedupe_key unique constraint",
            claim="leased foreign-only receipt claim",
            outcomes=["sent", "retryable_failed", "skipped", "terminal_failed"],
            ambiguity_policy="expired sending lease requires reconciliation/manual decision",
            readiness="broadcast complete only when every receipt is terminal",
            source_files=["core/services/telegram_admin_broadcast_delivery_service.py"],
            notes="Broadcast-level status is derived from per-recipient receipts.",
        ),
        _entry(
            "telegram_market_transition_notice",
            authority="foreign",
            provider="telegram",
            durability="durable_transition_receipt",
            causation="market transition and transition timestamp",
            destination_identity="configured market channel",
            idempotency="market_channel_notice_receipts.dedupe_key unique constraint",
            claim="foreign transition worker claim",
            outcomes=["sent", "retry_pending", "terminal_failed"],
            ambiguity_policy="unknown response is retained for bounded reconciliation",
            readiness="no overdue non-terminal market notice receipt",
            source_files=["core/services/market_transition_service.py"],
            notes="Market-open and market-close notices are foreign-local effects.",
        ),
        _entry(
            "telegram_registration_otp_and_handoff",
            authority="foreign",
            provider="telegram",
            durability="durable_otp_claim_or_idempotent_registration_command",
            causation="OTP challenge or registration command id",
            destination_identity="Telegram chat id",
            idempotency="OTP claim id or registration command receipt",
            claim="foreign OTP/registration claim",
            outcomes=["sent", "failed", "ambiguous", "already_processed"],
            ambiguity_policy="ambiguous provider start is preserved and not blindly retried",
            readiness="unresolved OTP and registration command claims",
            source_files=[
                "api/routers/auth.py",
                "bot/handlers/start.py",
                "core/services/telegram_otp_delivery_service.py",
            ],
            notes="Join-request replies are derived handoff messages; registration state remains authoritative in the durable command/OTP ledger.",
        ),
        _entry(
            "telegram_interactive_ui",
            authority="foreign",
            provider="telegram",
            durability="non_durable_derived_ui",
            causation="one Telegram update/callback handled by Bot-FI",
            destination_identity="originating chat and message",
            idempotency="Telegram update processing and persisted business command identity where mutation occurs",
            claim="single Bot update handler; no asynchronous business delivery promise",
            outcomes=["rendered", "best_effort_failed"],
            ambiguity_policy="never infer business commit from UI response; user can refresh/reissue",
            readiness="excluded from business convergence; monitored as Bot API error rate",
            source_files=[
                "bot/handlers/admin.py",
                "bot/handlers/admin_commodities.py",
                "bot/handlers/admin_users.py",
                "bot/handlers/trade_create.py",
                "bot/handlers/trade_execute.py",
                "bot/handlers/trade_history.py",
                "bot/message_manager.py",
                "bot/utils/trade_suggestion_messages.py",
                "core/utils.py",
            ],
            notes="Menus, callback acknowledgements, exports, and message cleanup are rebuildable UI—not durable business notifications.",
        ),
        _entry(
            "telegram_interaction_transport",
            authority="foreign",
            provider="telegram",
            durability="queue_v1_durable_transport_or_legacy_derived_ui",
            causation="Telegram update plus explicit interaction/pre-auth source key",
            destination_identity="originating Telegram chat and immutable recipient snapshot",
            idempotency="queue-v1 dedupe/source anchor; legacy mode owns one update handler",
            claim="queue-v1 leased worker claim or legacy synchronous handler ownership",
            outcomes=["enqueued", "sent", "expired", "cancelled", "legacy_best_effort_failed"],
            ambiguity_policy="queue-v1 preserves provider outcome and dependency anchors; legacy UI response never proves a business commit",
            readiness="queue-v1 due/ambiguous interaction backlog; legacy path contributes only provider error rate",
            source_files=[
                "bot/repeat_offer.py",
                "bot/telegram_interaction_message.py",
                "bot/telegram_pre_auth_interaction.py",
            ],
            notes="These adapters select durable queue ownership at runtime while retaining a fail-closed legacy compatibility path.",
        ),
        _entry(
            "webpush_market_and_notification",
            authority="webapp",
            provider="webpush",
            durability="same_transaction_fanout_then_per_endpoint_outbox",
            causation="immutable DR event in the authoritative business transaction",
            destination_identity="hash of exact push subscription endpoint",
            idempotency="event, effect type, and endpoint hash unique effect key",
            claim="Writer-epoch-bound leased effect worker",
            outcomes=["succeeded", "not_sent", "ambiguous", "cancelled_stale_epoch"],
            ambiguity_policy="ambiguous effect is never automatically retried; 404/410 only terminalizes that endpoint",
            readiness="no ambiguous effect and no due non-terminal endpoint effect",
            source_files=["api/routers/notifications.py", "core/web_push.py"],
            notes="Provider fanout is represented by one durable effect per subscription endpoint.",
        ),
        _entry(
            "sms_otp_and_invitation",
            authority="webapp",
            provider="smsir",
            durability="durable_domain_claim",
            causation="OTP challenge or invitation delivery row",
            destination_identity="normalized mobile hash plus domain record",
            idempotency="OTP claim id or invitation_sms_deliveries uniqueness",
            claim="domain ledger claim bridged through Writer-epoch capability immediately before send",
            outcomes=["accepted", "failed", "ambiguous", "disabled"],
            ambiguity_policy="provider-start ambiguity is persisted and never blindly retried",
            readiness="no expired/inflight ambiguous domain claim",
            source_files=[
                "api/routers/accountants.py",
                "api/routers/auth.py",
                "api/routers/customers.py",
                "api/routers/invitations.py",
                "core/services/otp_sms_delivery_service.py",
                "core/sms.py",
            ],
            notes="Existing specialized OTP/invitation ledgers remain authoritative; strict mode adds final Writer-term validation.",
        ),
        _entry(
            "sms_account_recovery",
            authority="webapp",
            provider="smsir",
            durability="same_transaction_generic_effect_outbox",
            causation="immutable recovery-request DR event",
            destination_identity="normalized mobile hash",
            idempotency="recovery request id and action",
            claim="Writer-epoch-bound leased effect worker",
            outcomes=["succeeded", "not_sent", "ambiguous", "cancelled_stale_epoch"],
            ambiguity_policy="ambiguous provider response is manual-review and not retried",
            readiness="no ambiguous recovery SMS effect",
            source_files=["api/routers/sessions.py", "core/sms.py"],
            notes="Informational recovery SMS is enqueued transactionally with the recovery state change.",
        ),
        _entry(
            "encrypted_blob_object_storage",
            authority="webapp",
            provider="s3_object_storage",
            durability="content_addressed_ciphertext_manifest_and_per_destination_delivery",
            causation="committed chat/file record and blob manifest",
            destination_identity="bucket, opaque object key, ciphertext hash, and provider version id",
            idempotency="plaintext content hash plus encryption context and destination",
            claim="leased blob delivery row",
            outcomes=["uploaded", "downloaded", "verified", "quarantined", "blocked"],
            ambiguity_policy="HEAD/read-back verification resolves response loss; untracked local residue is quarantined",
            readiness="ciphertext/version parity and no unresolved orphan quarantine item",
            source_files=["core/dr_audit_anchor.py", "core/dr_blob_worker.py"],
            notes="User bytes are client-side encrypted before leaving a site; S3 metadata contains no plaintext identity.",
        ),
        _entry(
            "realtime_redis_and_websocket",
            authority="webapp",
            provider="redis_websocket",
            durability="non_durable_derived_signal",
            causation="already committed database/event state",
            destination_identity="user/channel connection",
            idempotency="not required; clients reload canonical state after reconnect",
            claim="none; post-commit best-effort signal only",
            outcomes=["published", "dropped", "client_reloaded"],
            ambiguity_policy="never used as proof of commit or cross-site convergence",
            readiness="excluded from durable parity; connection health only",
            source_files=[
                "api/routers/offers.py",
                "api/routers/realtime.py",
                "api/routers/sync.py",
                "api/routers/trades.py",
                "core/events.py",
                "core/utils.py",
            ],
            notes="Redis/SSE/WebSocket traffic is a disposable wake-up hint over canonical database state.",
        ),
        _entry(
            "email",
            authority="none",
            provider="email",
            durability="not_configured",
            causation="none",
            destination_identity="none",
            idempotency="none",
            claim="none",
            outcomes=["not_present"],
            ambiguity_policy="adding an email provider requires a new durable inventory entry and tests",
            readiness="not applicable",
            source_files=[],
            notes="No runtime email provider exists at this revision.",
        ),
        _entry(
            "arvan_route_switch",
            authority="control_plane",
            provider="arvan_cdn",
            durability="Witness-reserved_failover_operation_ledger",
            causation="fresh signed failover plan and exact operation hash",
            destination_identity="allowlisted zone/record/origin transition",
            idempotency="global Witness reservation plus typed operation id",
            claim="independent Witness one-time reservation",
            outcomes=["confirmed", "lost_response", "failed", "fenced"],
            ambiguity_policy="read-after-write typed reconciliation; generic shell execution forbidden",
            readiness="route state must match target and public verification before completion",
            source_files=[
                "core/dr_command_orchestration_adapter.py",
                "core/dr_failover_orchestrator.py",
                "scripts/arvan_origin_switch.py",
            ],
            notes="The source CLI remains validation-only until a reviewed typed deployment backend is injected.",
        ),
    ]
    effects.sort(key=lambda item: item["name"])
    body = {
        "effects": effects,
        "schema": EFFECT_INVENTORY_SCHEMA,
        "surface_count": len(effects),
    }
    body["inventory_sha256"] = hashlib.sha256(
        json.dumps(body, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    return body


def render_three_site_effect_inventory() -> str:
    return json.dumps(
        build_three_site_effect_inventory(), ensure_ascii=False, indent=2, sort_keys=True
    ) + "\n"
