"""add_block_settings_to_users

Revision ID: 0ed74190b05a
Revises: 862d9168012a
Create Date: 2026-01-28 10:37:58.808876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed74190b05a'
down_revision: Union[str, None] = '862d9168012a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_blocks_blocker_id_blocked_id_key', 'user_blocks', type_='unique')
    op.create_index(op.f('ix_user_blocks_id'), 'user_blocks', ['id'], unique=False)
    op.create_unique_constraint('uq_blocker_blocked', 'user_blocks', ['blocker_id', 'blocked_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_blocker_blocked', 'user_blocks', type_='unique')
    op.drop_index(op.f('ix_user_blocks_id'), table_name='user_blocks')
    op.create_unique_constraint('user_blocks_blocker_id_blocked_id_key', 'user_blocks', ['blocker_id', 'blocked_id'])
    # ### end Alembic commands ###
