"""add_lot_sizes_to_offer

Revision ID: 133ae92d599b
Revises: 52f1430ac164
Create Date: 2025-12-15 12:17:43.323420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133ae92d599b'
down_revision: Union[str, None] = '52f1430ac164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('remaining_quantity', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('is_wholesale', sa.Boolean(), nullable=True))
    op.add_column('offers', sa.Column('lot_sizes', sa.JSON(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE offers SET is_wholesale = TRUE WHERE is_wholesale IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('offers', 'is_wholesale', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'lot_sizes')
    op.drop_column('offers', 'is_wholesale')
    op.drop_column('offers', 'remaining_quantity')
    # ### end Alembic commands ###
