"""Add forwarded_from_id to Message

Revision ID: 246d4a144e78
Revises: cc25b16a3321
Create Date: 2026-02-21 11:50:53.037683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246d4a144e78'
down_revision: Union[str, None] = 'cc25b16a3321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('forwarded_from_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_messages_forwarded_from', 'messages', 'users', ['forwarded_from_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_forwarded_from', 'messages', type_='foreignkey')
    op.drop_column('messages', 'forwarded_from_id')
    # ### end Alembic commands ###
