"""add_message_edit_delete

Revision ID: 369dc42d08cf
Revises: 18ef1cc918ef
Create Date: 2025-12-30 13:43:11.310133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369dc42d08cf'
down_revision: Union[str, None] = '18ef1cc918ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('messages', sa.Column('edit_history', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'edit_history')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###
