"""add_original_lot_sizes

Revision ID: 3a122cbc5098
Revises: c2c44173cc44
Create Date: 2025-12-27 12:14:56.220290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a122cbc5098'
down_revision: Union[str, None] = 'c2c44173cc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('original_lot_sizes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'original_lot_sizes')
    # ### end Alembic commands ###
