"""add_version_id_to_trades

Revision ID: 3a87114f0df6
Revises: 7c81370e9cdb
Create Date: 2025-12-24 12:34:40.678099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a87114f0df6'
down_revision: Union[str, None] = '7c81370e9cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.add_column('trades', sa.Column('version_id', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('trades', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_trades_created_at', 'trades', ['created_at'], unique=False)
    op.create_index('ix_trades_status_offer_user', 'trades', ['status', 'offer_user_id'], unique=False)
    op.create_index('ix_trades_status_responder', 'trades', ['status', 'responder_user_id'], unique=False)
    op.alter_column('trading_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('user_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'created_at')
    op.alter_column('trading_settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('ix_trades_status_responder', table_name='trades')
    op.drop_index('ix_trades_status_offer_user', table_name='trades')
    op.drop_index('ix_trades_created_at', table_name='trades')
    op.drop_column('trades', 'updated_at')
    op.drop_column('trades', 'version_id')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
