"""add_soft_delete_to_user_model

Revision ID: 3d8209d358c8
Revises: 6e7ad5733d5a
Create Date: 2025-12-23 10:46:31.421269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8209d358c8'
down_revision: Union[str, None] = '6e7ad5733d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # اضافه کردن is_deleted با مقدار پیش‌فرض False برای کاربران موجود
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.execute("UPDATE users SET is_deleted = false WHERE is_deleted IS NULL")
    op.alter_column('users', 'is_deleted', nullable=False)
    op.alter_column('users', 'is_deleted', server_default=None)
    
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
