"""sync_log_tables

Revision ID: 5061c56d11e7
Revises: 0ed74190b05a
Create Date: 2026-02-09 13:49:57.684631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5061c56d11e7'
down_revision: Union[str, None] = '0ed74190b05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync', 'change_log', ['synced', 'created_at'], unique=False)
    op.create_index('idx_table', 'change_log', ['table_name', 'record_id'], unique=False)
    op.create_index(op.f('ix_change_log_id'), 'change_log', ['id'], unique=False)
    op.create_table('sync_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'date', name='uq_source_date')
    )
    op.create_index(op.f('ix_sync_blocks_id'), 'sync_blocks', ['id'], unique=False)
    
    # Add columns to offers
    op.add_column('offers', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.add_column('offers', sa.Column('archived', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'offers', ['idempotency_key'])
    
    # Add columns to trades
    op.add_column('trades', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.add_column('trades', sa.Column('archived', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'trades', ['idempotency_key'])
    
    # Add columns to users (with safe defaults)
    # Add columns to users (with safe defaults) - ALREADY EXIST IN LOCAL DB
    # op.add_column('users', sa.Column('max_daily_trades', sa.Integer(), nullable=True))
    # op.add_column('users', sa.Column('max_active_commodities', sa.Integer(), nullable=True))
    # op.add_column('users', sa.Column('max_daily_requests', sa.Integer(), nullable=True))
    # op.add_column('users', sa.Column('limitations_expire_at', sa.DateTime(), nullable=True))
    # Added server_default=sa.false() and sa.text('50')
    # op.add_column('users', sa.Column('can_block_users', sa.Boolean(), nullable=False, server_default=sa.false()))
    # op.add_column('users', sa.Column('max_blocked_users', sa.Integer(), nullable=False, server_default=sa.text('50')))
    # op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'updated_at')
    # op.drop_column('users', 'max_blocked_users')
    # op.drop_column('users', 'can_block_users')
    # op.drop_column('users', 'limitations_expire_at')
    # op.drop_column('users', 'max_daily_requests')
    # op.drop_column('users', 'max_active_commodities')
    # op.drop_column('users', 'max_daily_trades')
    op.drop_constraint(None, 'trades', type_='unique')
    op.drop_column('trades', 'archived')
    op.drop_column('trades', 'idempotency_key')
    op.drop_constraint(None, 'offers', type_='unique')
    op.drop_column('offers', 'archived')
    op.drop_column('offers', 'idempotency_key')
    op.drop_index(op.f('ix_sync_blocks_id'), table_name='sync_blocks')
    op.drop_table('sync_blocks')
    op.drop_index(op.f('ix_change_log_id'), table_name='change_log')
    op.drop_index('idx_table', table_name='change_log')
    op.drop_index('idx_sync', table_name='change_log')
    op.drop_table('change_log')
    # ### end Alembic commands ###
