"""nullable_user_fks_and_mobile_fields

Revision ID: 52f1430ac164
Revises: 58c158f81bf5
Create Date: 2025-12-15 10:25:07.705134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f1430ac164'
down_revision: Union[str, None] = '58c158f81bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('offers_user_id_fkey', 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('trades', sa.Column('offer_user_mobile', sa.String(length=20), nullable=True))
    op.add_column('trades', sa.Column('responder_user_mobile', sa.String(length=20), nullable=True))
    op.alter_column('trades', 'offer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trades', 'offer_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trades', 'responder_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('trades_offer_user_id_fkey', 'trades', type_='foreignkey')
    op.drop_constraint('trades_responder_user_id_fkey', 'trades', type_='foreignkey')
    op.drop_constraint('trades_offer_id_fkey', 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'users', ['responder_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trades', 'offers', ['offer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trades', 'users', ['offer_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key('trades_offer_id_fkey', 'trades', 'offers', ['offer_id'], ['id'])
    op.create_foreign_key('trades_responder_user_id_fkey', 'trades', 'users', ['responder_user_id'], ['id'])
    op.create_foreign_key('trades_offer_user_id_fkey', 'trades', 'users', ['offer_user_id'], ['id'])
    op.alter_column('trades', 'responder_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trades', 'offer_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trades', 'offer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('trades', 'responder_user_mobile')
    op.drop_column('trades', 'offer_user_mobile')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key('offers_user_id_fkey', 'offers', 'users', ['user_id'], ['id'])
    op.alter_column('offers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
