"""add_trade_number

Revision ID: 58c158f81bf5
Revises: offers_trades_v2
Create Date: 2025-12-14 12:53:15.019150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c158f81bf5'
down_revision: Union[str, None] = 'offers_trades_v2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_offers_created_at', table_name='offers')
    op.drop_index('ix_offers_status', table_name='offers')
    op.drop_index('ix_offers_user_id', table_name='offers')
    op.add_column('trades', sa.Column('trade_number', sa.Integer(), nullable=False))
    op.drop_index('ix_trades_created_at', table_name='trades')
    op.drop_index('ix_trades_offer_user_id', table_name='trades')
    op.drop_index('ix_trades_responder_user_id', table_name='trades')
    op.drop_index('ix_trades_status', table_name='trades')
    op.create_index(op.f('ix_trades_trade_number'), 'trades', ['trade_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_number'), table_name='trades')
    op.create_index('ix_trades_status', 'trades', ['status'], unique=False)
    op.create_index('ix_trades_responder_user_id', 'trades', ['responder_user_id'], unique=False)
    op.create_index('ix_trades_offer_user_id', 'trades', ['offer_user_id'], unique=False)
    op.create_index('ix_trades_created_at', 'trades', ['created_at'], unique=False)
    op.drop_column('trades', 'trade_number')
    op.create_index('ix_offers_user_id', 'offers', ['user_id'], unique=False)
    op.create_index('ix_offers_status', 'offers', ['status'], unique=False)
    op.create_index('ix_offers_created_at', 'offers', ['created_at'], unique=False)
    # ### end Alembic commands ###
