"""add_reply_to_message_with_name

Revision ID: 5efbaab16e48
Revises: 369dc42d08cf
Create Date: 2026-01-04 08:15:27.168329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efbaab16e48'
down_revision: Union[str, None] = '369dc42d08cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_messages_reply_to_message', 'messages', 'messages', ['reply_to_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_reply_to_message', 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_message_id')
    # ### end Alembic commands ###
