"""Add chat_files table

Revision ID: 6a5704ca78cd
Revises: 246d4a144e78
Create Date: 2026-02-23 12:15:40.648132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5704ca78cd'
down_revision: Union[str, None] = '246d4a144e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_files_created_at'), 'chat_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_files_id'), 'chat_files', ['id'], unique=False)
    op.create_index(op.f('ix_chat_files_uploader_id'), 'chat_files', ['uploader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_files_uploader_id'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_id'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_created_at'), table_name='chat_files')
    op.drop_table('chat_files')
    # ### end Alembic commands ###
