"""Add commodity and commodity_alias tables

Revision ID: 789bf8b955f7
Revises: accd5c88ad9d
Create Date: 2025-10-26 10:10:04.844410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789bf8b955f7'
down_revision: Union[str, None] = 'accd5c88ad9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_id'), 'commodities', ['id'], unique=False)
    op.create_index(op.f('ix_commodities_name'), 'commodities', ['name'], unique=True)
    op.create_table('commodity_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodity_aliases_alias'), 'commodity_aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_commodity_aliases_id'), 'commodity_aliases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commodity_aliases_id'), table_name='commodity_aliases')
    op.drop_index(op.f('ix_commodity_aliases_alias'), table_name='commodity_aliases')
    op.drop_table('commodity_aliases')
    op.drop_index(op.f('ix_commodities_name'), table_name='commodities')
    op.drop_index(op.f('ix_commodities_id'), table_name='commodities')
    op.drop_table('commodities')
    # ### end Alembic commands ###
