"""add_composite_index_status_commodity_to_offers

Revision ID: 7c81370e9cdb
Revises: 3d8209d358c8
Create Date: 2025-12-23 10:57:56.724426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c81370e9cdb'
down_revision: Union[str, None] = '3d8209d358c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_offers_status_commodity', 'offers', ['status', 'commodity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_offers_status_commodity', table_name='offers')
    # ### end Alembic commands ###
