"""add_trading_settings_table

Revision ID: 8afb40fdbd38
Revises: 7501fae7c9a4
Create Date: 2025-12-23 10:03:25.912917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afb40fdbd38'
down_revision: Union[str, None] = '7501fae7c9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_trading_settings_key'), 'trading_settings', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_settings_key'), table_name='trading_settings')
    op.drop_table('trading_settings')
    # ### end Alembic commands ###
