"""Add user_sessions table

Revision ID: accd5c88ad9d
Revises: 22a2e065ec82
Create Date: 2025-10-09 08:19:25.898360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accd5c88ad9d'
down_revision: Union[str, None] = '22a2e065ec82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('TELEGRAM_MINI_APP', 'WEB', 'ANDROID', name='platform'), nullable=False),
    sa.Column('device_fingerprint', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_device_fingerprint'), 'user_sessions', ['device_fingerprint'], unique=True)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_fingerprint'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
