"""add_republished_offer_id

Revision ID: c2c44173cc44
Revises: 3a87114f0df6
Create Date: 2025-12-27 12:02:23.677362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c44173cc44'
down_revision: Union[str, None] = '3a87114f0df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('republished_offer_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'republished_offer_id')
    # ### end Alembic commands ###
