"""add_version_id_to_offers_for_optimistic_locking

Revision ID: d3f557edf163
Revises: 8afb40fdbd38
Create Date: 2025-12-23 10:26:37.211884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f557edf163'
down_revision: Union[str, None] = '8afb40fdbd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # اضافه کردن ستون با مقدار پیش‌فرض برای سطرهای موجود
    # ابتدا به صورت nullable اضافه می‌کنیم
    op.add_column('offers', sa.Column('version_id', sa.Integer(), nullable=True, server_default='1'))
    
    # آپدیت سطرهای موجود که NULL هستند
    op.execute("UPDATE offers SET version_id = 1 WHERE version_id IS NULL")
    
    # تغییر به NOT NULL بعد از آپدیت
    op.alter_column('offers', 'version_id', nullable=False)
    
    # حذف server_default (اختیاری، برای تمیزی)
    op.alter_column('offers', 'version_id', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'version_id')
    # ### end Alembic commands ###
