"""Use a permanent mutation-capture relation for PostgreSQL 2PC.

The original strict event-fence implementation used a temporary table to bind
an ORM mutation to its immutable DR event. PostgreSQL rejects
``PREPARE TRANSACTION`` after any temporary relation has been touched. The
same-region journal therefore could never coordinate a real authoritative
write. This forward-only migration keeps the capture relation owner-protected
and keyed by the source xid; rollback still removes rows transactionally and a
bounded maintenance command can prune committed history.
"""

from __future__ import annotations

import importlib

from alembic import op


revision = "f2c3d4e5a6b7"
down_revision = "e0a4b6c8d1e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.dr_authoritative_mutations (
            capture_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_xid bigint NOT NULL,
            origin_authority text NOT NULL,
            origin_physical_site text NOT NULL,
            writer_epoch bigint,
            aggregate_type text NOT NULL,
            aggregate_db_id text NOT NULL,
            operation text NOT NULL,
            row_payload jsonb NOT NULL,
            captured_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            CONSTRAINT ck_dr_authoritative_mutations_operation
                CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE'))
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_dr_authoritative_mutations_lookup
        ON public.dr_authoritative_mutations
            (source_xid, aggregate_type, aggregate_db_id, operation)
        """
    )

    source = importlib.import_module(
        "migrations.versions.e653f4a5b7c8_close_three_site_database_trust_gaps"
    )
    # Keep the original security migration immutable.  Derive the repaired
    # trigger bodies from its reviewed SQL and replace only the temp-relation
    # boundary.  This keeps clean installs and forward upgrades aligned while
    # preserving the executed migration's hash.
    mutation_sql = source.MUTATION_CAPTURE_SQL
    mutation_sql = mutation_sql.replace(
        "capture_relation := to_regclass('pg_temp.trading_bot_authoritative_mutations');",
        "capture_relation := to_regclass('public.dr_authoritative_mutations');",
    ).replace(
        """    IF capture_relation IS NULL THEN
        CREATE TEMP TABLE trading_bot_authoritative_mutations (
            source_xid bigint NOT NULL,
            origin_authority text NOT NULL,
            origin_physical_site text NOT NULL,
            writer_epoch bigint,
            aggregate_type text NOT NULL,
            aggregate_db_id text NOT NULL,
            operation text NOT NULL,
            row_payload jsonb NOT NULL
        ) ON COMMIT DELETE ROWS;
        CREATE INDEX ON trading_bot_authoritative_mutations (
            source_xid, aggregate_type, aggregate_db_id, operation
        );
        REVOKE ALL ON TABLE trading_bot_authoritative_mutations FROM PUBLIC;
        capture_relation := to_regclass('pg_temp.trading_bot_authoritative_mutations');
    END IF;""",
        """    IF capture_relation IS NULL THEN
        RAISE EXCEPTION 'authoritative mutation capture relation is missing';
    END IF;""",
    ).replace(
        "AND relation.relpersistence = 't'",
        "AND relation.relpersistence = 'p'",
    ).replace(
        "INSERT INTO pg_temp.trading_bot_authoritative_mutations (",
        "INSERT INTO public.dr_authoritative_mutations (",
    )
    event_sql = source.EVENT_COVERAGE_SQL.replace(
        "pg_temp.trading_bot_authoritative_mutations",
        "public.dr_authoritative_mutations",
    )
    op.execute(mutation_sql)
    op.execute(event_sql)


def downgrade() -> None:
    raise RuntimeError(
        "f2c3d4e5a6b7 is forward-only; preserve the 2PC-safe capture boundary"
    )
