"""add expiry and foreign key to invitations table

Revision ID: f608919eecbf
Revises: 17edb7222a4c
Create Date: 2025-11-15 12:34:30.760061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f608919eecbf'
down_revision: Union[str, None] = '17edb7222a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('invitations', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'invitations', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'expires_at')
    op.drop_column('invitations', 'created_by_id')
    # ### end Alembic commands ###
