"""Explicit, append-only persistence for catalog-bound inference decisions."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import re

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from models.coin_intelligence_inference_audit import CoinIntelligenceInferenceAudit

from .coin_catalog import (
    COIN_CATALOG_RESOLUTION_VERSION,
    CatalogCoinCommodityInference,
)
from .coin_inference import (
    CANONICAL_COMMODITY_NAMES,
    COIN_INFERENCE_VERSION,
    normalize_coin_inference_candidate_scope,
)
from .market_contracts import normalize_utc


_DECISION_KEY_PATTERN = re.compile(r"^[a-f0-9]{64}$")
_REASON_CODE_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]{0,95}$")
_SOURCE_CODE_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]{0,63}$")
_SOURCE_SURFACES = frozenset({"WEBAPP", "TELEGRAM_BOT", "INTERNAL"})
_MARKET_REGIMES = frozenset({"NORMAL", "UP", "DOWN", "VOLATILE", "UNKNOWN"})


class CoinInferenceAuditConflictError(ValueError):
    """The idempotency key was reused for a different economic decision."""


@dataclass(frozen=True, slots=True)
class CoinInferenceAuditCommand:
    """Minimal data required to record one proposed inference decision.

    ``decision_key`` is opaque and generated by the caller.  It must never be
    derived from a user, message, offer, or Telegram identifier.
    """

    decision_key: str
    source_surface: str
    submitted_project_price: int
    decision: CatalogCoinCommodityInference
    candidate_scope: str = "ALL"
    # These are frozen from the exact local Snapshot used by the decision.
    # They are source/model metadata only; never raw market text or identity.
    dominant_underlying_source: str | None = None
    market_regime: str = "UNKNOWN"


def _normalized_key(value: str) -> str:
    normalized = str(value or "").strip().lower()
    if not _DECISION_KEY_PATTERN.fullmatch(normalized):
        raise ValueError("coin_inference_audit_key_invalid")
    return normalized


def _normalized_source_surface(value: str) -> str:
    normalized = str(value or "").strip().upper()
    if normalized not in _SOURCE_SURFACES:
        raise ValueError("coin_inference_audit_source_surface_invalid")
    return normalized


def _snapshot_time(value: str | None) -> datetime | None:
    if value is None:
        return None
    normalized = normalize_utc(value, field_name="coin_inference_audit_snapshot_generated_at_utc")
    return datetime.fromisoformat(normalized.replace("Z", "+00:00"))


def _market_context(command: CoinInferenceAuditCommand) -> tuple[str | None, str]:
    source = command.dominant_underlying_source
    if source is not None:
        source = str(source).strip().upper()
        if not _SOURCE_CODE_PATTERN.fullmatch(source):
            raise ValueError("coin_inference_audit_underlying_source_invalid")
    regime = str(command.market_regime or "UNKNOWN").strip().upper()
    if regime not in _MARKET_REGIMES:
        raise ValueError("coin_inference_audit_market_regime_invalid")
    return source, regime


def _record_values(command: CoinInferenceAuditCommand) -> dict[str, object]:
    price = int(command.submitted_project_price)
    if price <= 0:
        raise ValueError("coin_inference_audit_price_invalid")
    decision = command.decision
    if decision.status not in {"AUTO_SELECT", "CONFIRM", "ABSTAIN"}:
        raise ValueError("coin_inference_audit_status_invalid")
    candidate_scope = normalize_coin_inference_candidate_scope(command.candidate_scope)
    if decision.settlement_term not in {"CASH", "TOMORROW"}:
        raise ValueError("coin_inference_audit_settlement_invalid")
    receipt = decision.snapshot_receipt
    if receipt is not None and not _DECISION_KEY_PATTERN.fullmatch(str(receipt)):
        raise ValueError("coin_inference_audit_snapshot_receipt_invalid")
    reason = decision.reason
    if reason is not None and not _REASON_CODE_PATTERN.fullmatch(str(reason)):
        raise ValueError("coin_inference_audit_reason_invalid")
    candidate_count = len(decision.candidates)
    selected = None
    seen_catalog_ids: set[int] = set()
    for candidate in decision.candidates:
        try:
            catalog_id = int(candidate.commodity_id)
        except (TypeError, ValueError) as exc:
            raise ValueError("coin_inference_audit_catalog_id_invalid") from exc
        if (
            catalog_id <= 0
            or catalog_id in seen_catalog_ids
            or CANONICAL_COMMODITY_NAMES.get(candidate.commodity_code) != candidate.commodity_name
        ):
            raise ValueError("coin_inference_audit_catalog_candidate_invalid")
        seen_catalog_ids.add(catalog_id)
    if decision.status == "AUTO_SELECT":
        if candidate_count != 1:
            raise ValueError("coin_inference_audit_auto_select_shape_invalid")
        selected = decision.candidates[0]
    elif decision.status == "CONFIRM":
        if candidate_count < 1:
            raise ValueError("coin_inference_audit_confirm_shape_invalid")
    elif candidate_count:
        raise ValueError("coin_inference_audit_abstain_shape_invalid")
    if decision.status in {"AUTO_SELECT", "CONFIRM"} and (receipt is None or decision.snapshot_generated_at_utc is None):
        raise ValueError("coin_inference_audit_snapshot_provenance_required")
    dominant_underlying_source, market_regime = _market_context(command)
    return {
        "decision_key": _normalized_key(command.decision_key),
        "source_surface": _normalized_source_surface(command.source_surface),
        "decision_status": decision.status,
        "reason_code": str(reason) if reason is not None else None,
        "settlement_term": decision.settlement_term,
        "candidate_scope": candidate_scope,
        "submitted_project_price": price,
        "candidate_count": candidate_count,
        "selected_commodity_id": int(selected.commodity_id) if selected else None,
        "selected_commodity_code": selected.commodity_code if selected else None,
        "selected_commodity_name": selected.commodity_name if selected else None,
        "inference_version": COIN_INFERENCE_VERSION,
        "catalog_resolution_version": COIN_CATALOG_RESOLUTION_VERSION,
        "snapshot_receipt": str(receipt) if receipt is not None else None,
        "snapshot_generated_at_utc": _snapshot_time(decision.snapshot_generated_at_utc),
        "dominant_underlying_source": dominant_underlying_source,
        "market_regime": market_regime,
    }


def _same_record(record: CoinIntelligenceInferenceAudit, values: dict[str, object]) -> bool:
    fields = (
        "source_surface",
        "decision_status",
        "reason_code",
        "settlement_term",
        "candidate_scope",
        "submitted_project_price",
        "candidate_count",
        "selected_commodity_id",
        "selected_commodity_code",
        "selected_commodity_name",
        "inference_version",
        "catalog_resolution_version",
        "snapshot_receipt",
        "snapshot_generated_at_utc",
        "dominant_underlying_source",
        "market_regime",
    )
    return all(getattr(record, field, None) == values[field] for field in fields)


async def append_coin_inference_audit(
    db: AsyncSession,
    command: CoinInferenceAuditCommand,
) -> CoinIntelligenceInferenceAudit:
    """Append a new audit row or return the exact idempotent prior row.

    The caller owns the surrounding transaction.  This function issues no
    commit, update, offer creation, model call, or background task.
    """

    values = _record_values(command)
    result = await db.execute(
        select(CoinIntelligenceInferenceAudit).where(
            CoinIntelligenceInferenceAudit.decision_key == values["decision_key"]
        )
    )
    existing = result.scalar_one_or_none()
    if existing is not None:
        if not _same_record(existing, values):
            raise CoinInferenceAuditConflictError("coin_inference_audit_idempotency_conflict")
        return existing
    record = CoinIntelligenceInferenceAudit(**values)
    db.add(record)
    await db.flush()
    return record


async def load_coin_inference_audit(
    db: AsyncSession,
    *,
    decision_key: str,
) -> CoinIntelligenceInferenceAudit | None:
    """Read one opaque decision receipt after strict local validation."""

    normalized_key = _normalized_key(decision_key)
    result = await db.execute(
        select(CoinIntelligenceInferenceAudit).where(
            CoinIntelligenceInferenceAudit.decision_key == normalized_key
        )
    )
    return result.scalar_one_or_none()


__all__ = [
    "CoinInferenceAuditCommand",
    "CoinInferenceAuditConflictError",
    "append_coin_inference_audit",
    "load_coin_inference_audit",
]
