#!/usr/bin/env python3
"""One-shot Object-Storage relay for a DNS-01 certificate issued on WA-IR.

The private ACME key is generated by ``lego`` on WebApp-IR.  WebApp-IR never
receives an Arvan API token or an S3 credential: it sends only a short-lived,
signed challenge request to private Arvan Object Storage.  This controller
process owns the DNS token, creates/removes the exact TXT record, and returns a
short-lived acknowledgement through that same Object Storage mailbox.

There are three intentionally small commands:

``provision``
    Upload this non-secret hook plus an expiring operation descriptor and
    write a root-only SSH bootstrap descriptor.
``serve``
    Run on the controller for one operation.  It accepts only one exact
    ``_acme-challenge.coin.gold-trade.ir.`` TXT name and cleans a record on
    timeout.
``hook``
    Run on WA-IR by lego's ``exec`` DNS provider.  It has only presigned URLs,
    not S3/API credentials, and waits for the controller acknowledgement.

No subcommand changes the production A record.  The relay is intentionally
single-domain and short-lived rather than a general DNS administration tool.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import sys
import time
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlsplit
from urllib.request import HTTPRedirectHandler, Request, build_opener
from uuid import uuid4


SCHEMA = "emergency-ir-acme-dns-relay-v1"
OBJECT_STORAGE_HOST = "s3.ir-thr-at1.arvanstorage.ir"
OBJECT_STORAGE_ENDPOINT = f"https://{OBJECT_STORAGE_HOST}"
OBJECT_STORAGE_REGION = "ir-thr-at1"
ARVAN_API_BASE = "https://napi.arvancloud.ir/cdn/4.0"
DOMAIN = "gold-trade.ir"
TARGET_HOST = "coin.gold-trade.ir"
TARGET_FQDN = "_acme-challenge.coin.gold-trade.ir."
TARGET_RECORD_NAME = "_acme-challenge.coin"
TTL = 600
MAX_OPERATION_SECONDS = 900
MAX_JSON_BYTES = 32 * 1024
OPERATION_RE = re.compile(r"^[0-9a-f]{32}$")
VALUE_RE = re.compile(r"^[A-Za-z0-9_-]{20,160}$")
PREFIX_RE = re.compile(r"^[a-z0-9][a-z0-9./_-]{4,180}$")


class RelayError(RuntimeError):
    """Raised for a fail-closed relay operation."""


class _NoRedirect(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):  # noqa: ANN001
        raise RelayError("redirects are forbidden")


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _json_bytes(value: dict[str, Any]) -> bytes:
    return (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def _safe_regular(
    path: Path,
    *,
    label: str,
    max_bytes: int = MAX_JSON_BYTES,
    private: bool = True,
) -> bytes:
    try:
        descriptor = os.open(path, os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0))
    except OSError as exc:
        raise RelayError(f"cannot securely open {label}") from exc
    try:
        before = os.fstat(descriptor)
        if (
            not stat.S_ISREG(before.st_mode)
            or before.st_uid != os.geteuid()
            or before.st_nlink != 1
            or (private and stat.S_IMODE(before.st_mode) & 0o077)
            or before.st_size <= 0
            or before.st_size > max_bytes
        ):
            raise RelayError(f"{label} is not one bounded private regular file")
        chunks: list[bytes] = []
        remaining = max_bytes + 1
        while remaining:
            chunk = os.read(descriptor, min(65_536, remaining))
            if not chunk:
                break
            chunks.append(chunk)
            remaining -= len(chunk)
        payload = b"".join(chunks)
        after = os.fstat(descriptor)
        if len(payload) > max_bytes or any(
            getattr(before, field) != getattr(after, field)
            for field in ("st_dev", "st_ino", "st_mode", "st_uid", "st_nlink", "st_size")
        ):
            raise RelayError(f"{label} changed while it was read")
        return payload
    finally:
        os.close(descriptor)


def _read_json(path: Path, *, label: str) -> dict[str, Any]:
    try:
        value = json.loads(_safe_regular(path, label=label).decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RelayError(f"{label} is not valid JSON") from exc
    if not isinstance(value, dict):
        raise RelayError(f"{label} must be a JSON object")
    return value


def _write_private_json(path: Path, value: dict[str, Any], *, label: str) -> None:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    if stat.S_IMODE(path.parent.stat().st_mode) & 0o077:
        raise RelayError(f"{label} parent must be private")
    payload = _json_bytes(value)
    temporary = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
    descriptor = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0), 0o600)
    try:
        with os.fdopen(descriptor, "wb", closefd=False) as raw:
            raw.write(payload)
            raw.flush()
            os.fsync(raw.fileno())
        os.close(descriptor)
        descriptor = -1
        os.replace(temporary, path)
        os.chmod(path, 0o600)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        temporary.unlink(missing_ok=True)


def _read_token(path: Path, *, label: str) -> str:
    value = _safe_regular(path, label=label).decode("utf-8").strip()
    if not value or "\n" in value or "\r" in value:
        raise RelayError(f"{label} is malformed")
    return value


def _parse_credentials(path: Path) -> tuple[str, str, str, str]:
    values: dict[str, str] = {}
    for raw in _safe_regular(path, label="Object Storage credentials").decode("utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise RelayError("Object Storage credentials are malformed")
        key, value = line.split("=", 1)
        if key in values:
            raise RelayError("Object Storage credentials contain duplicate keys")
        values[key] = value
    required = {"ARVAN_S3_ACCESS_KEY", "ARVAN_S3_SECRET_KEY", "ARVAN_S3_ENDPOINT", "ARVAN_S3_REGION"}
    if set(values) != required:
        raise RelayError("Object Storage credential fields are invalid")
    if values["ARVAN_S3_ENDPOINT"].rstrip("/") != OBJECT_STORAGE_ENDPOINT or values["ARVAN_S3_REGION"] != OBJECT_STORAGE_REGION:
        raise RelayError("Object Storage endpoint or region drifted")
    if len(values["ARVAN_S3_ACCESS_KEY"]) < 8 or len(values["ARVAN_S3_SECRET_KEY"]) < 32:
        raise RelayError("Object Storage credentials are malformed")
    return (
        values["ARVAN_S3_ACCESS_KEY"],
        values["ARVAN_S3_SECRET_KEY"],
        values["ARVAN_S3_ENDPOINT"],
        values["ARVAN_S3_REGION"],
    )


def _client(credentials: tuple[str, str, str, str]):
    try:
        import boto3
    except ModuleNotFoundError as exc:  # pragma: no cover - host prerequisite
        raise RelayError("boto3 is required on the controller") from exc
    access, secret, endpoint, region = credentials
    return boto3.client(
        "s3",
        endpoint_url=endpoint,
        region_name=region,
        aws_access_key_id=access,
        aws_secret_access_key=secret,
    )


def _require_private_versioned_bucket(client, bucket: str) -> None:  # noqa: ANN001
    if client.get_bucket_versioning(Bucket=bucket).get("Status") != "Enabled":
        raise RelayError("Object Storage bucket must be versioned")
    acl = client.get_bucket_acl(Bucket=bucket)
    for grant in acl.get("Grants", []):
        grantee = grant.get("Grantee") if isinstance(grant, dict) else None
        uri = str(grantee.get("URI") or "") if isinstance(grantee, dict) else ""
        if uri.endswith("/AllUsers") or uri.endswith("/AuthenticatedUsers"):
            raise RelayError("Object Storage bucket must not be public")


def _validate_object_url(value: str, *, label: str) -> str:
    parsed = urlsplit(value)
    if (
        parsed.scheme != "https"
        or parsed.hostname != OBJECT_STORAGE_HOST
        or parsed.username
        or parsed.password
        or parsed.port not in (None, 443)
        or not parsed.path.startswith("/")
        or not parsed.query
    ):
        raise RelayError(f"{label} is not an approved presigned Object Storage URL")
    return value


def _safe_prefix(value: str) -> str:
    normalized = str(value).strip("/")
    if not PREFIX_RE.fullmatch(normalized) or ".." in Path(normalized).parts:
        raise RelayError("Object Storage prefix is invalid")
    return normalized


def _safe_operation(value: Any) -> str:
    operation = str(value or "")
    if not OPERATION_RE.fullmatch(operation):
        raise RelayError("operation id is invalid")
    return operation


def _validate_descriptor(value: dict[str, Any]) -> dict[str, Any]:
    if value.get("schema") != SCHEMA:
        raise RelayError("relay descriptor schema is invalid")
    operation = _safe_operation(value.get("operation_id"))
    if value.get("domain") != DOMAIN or value.get("target_fqdn") != TARGET_FQDN:
        raise RelayError("relay descriptor domain scope drifted")
    try:
        deadline = int(value.get("deadline_epoch"))
    except (TypeError, ValueError) as exc:
        raise RelayError("relay descriptor deadline is invalid") from exc
    now = int(time.time())
    if deadline <= now or deadline > now + MAX_OPERATION_SECONDS + 60:
        raise RelayError("relay descriptor deadline is outside the bounded window")
    request_url = _validate_object_url(str(value.get("request_put_url") or ""), label="request URL")
    response_url = _validate_object_url(str(value.get("response_get_url") or ""), label="response URL")
    return {
        "schema": SCHEMA,
        "operation_id": operation,
        "domain": DOMAIN,
        "target_fqdn": TARGET_FQDN,
        "deadline_epoch": deadline,
        "request_put_url": request_url,
        "response_get_url": response_url,
    }


def _validate_request(value: dict[str, Any], descriptor: dict[str, Any]) -> dict[str, Any]:
    if value.get("schema") != SCHEMA or value.get("operation_id") != descriptor["operation_id"]:
        raise RelayError("relay request operation is invalid")
    action = value.get("action")
    if action not in {"present", "cleanup"}:
        raise RelayError("relay request action is invalid")
    if value.get("fqdn") != TARGET_FQDN:
        raise RelayError("relay request DNS name is outside the exact allowlist")
    challenge = str(value.get("value") or "")
    if not VALUE_RE.fullmatch(challenge):
        raise RelayError("relay request challenge value is invalid")
    request_id = _safe_operation(str(value.get("request_id") or ""))
    return {"schema": SCHEMA, "operation_id": descriptor["operation_id"], "action": action, "fqdn": TARGET_FQDN, "value": challenge, "request_id": request_id}


def _response(request: dict[str, Any], *, status: str, error: str | None = None) -> dict[str, Any]:
    result: dict[str, Any] = {
        "schema": SCHEMA,
        "operation_id": request["operation_id"],
        "action": request["action"],
        "request_id": request["request_id"],
        "status": status,
        "timestamp": _utc_now(),
    }
    if error:
        result["error"] = error[:240]
    return result


def _http_json(method: str, url: str, *, payload: dict[str, Any] | None = None, allow_404: bool = False) -> dict[str, Any] | None:
    body = _json_bytes(payload) if payload is not None else None
    headers = {"Accept": "application/json", "User-Agent": "trading-bot-emergency-ir-acme-relay/1"}
    if body is not None:
        headers["Content-Type"] = "application/json"
    request = Request(url, data=body, method=method, headers=headers)
    try:
        with build_opener(_NoRedirect()).open(request, timeout=20) as response:
            raw = response.read(MAX_JSON_BYTES + 1)
    except HTTPError as exc:
        if allow_404 and exc.code == 404:
            return None
        raise RelayError(f"relay HTTP request failed with status {exc.code}") from exc
    except URLError as exc:
        raise RelayError("relay HTTP request is unavailable") from exc
    if not raw:
        return {}
    if len(raw) > MAX_JSON_BYTES:
        raise RelayError("relay HTTP response exceeds its bounded size")
    try:
        decoded = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RelayError("relay HTTP response is not JSON") from exc
    if not isinstance(decoded, dict):
        raise RelayError("relay HTTP response is not a JSON object")
    return decoded


def _arvan_request(token: str, method: str, path: str, payload: dict[str, Any] | None = None) -> dict[str, Any]:
    if not path.startswith("/") or ".." in Path(path).parts:
        raise RelayError("Arvan API path is invalid")
    body = _json_bytes(payload) if payload is not None else None
    headers = {
        "Accept": "application/json",
        "Authorization": f"Apikey {token}",
        "User-Agent": "trading-bot-emergency-ir-acme-relay/1",
    }
    if body is not None:
        headers["Content-Type"] = "application/json"
    request = Request(f"{ARVAN_API_BASE}{path}", data=body, method=method, headers=headers)
    try:
        with build_opener(_NoRedirect()).open(request, timeout=20) as response:
            raw = response.read(MAX_JSON_BYTES + 1)
    except HTTPError as exc:
        raise RelayError(f"Arvan DNS API failed with status {exc.code}") from exc
    except URLError as exc:
        raise RelayError("Arvan DNS API is unavailable") from exc
    if len(raw) > MAX_JSON_BYTES:
        raise RelayError("Arvan DNS API response exceeds its bounded size")
    try:
        decoded = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RelayError("Arvan DNS API response is not JSON") from exc
    if not isinstance(decoded, dict):
        raise RelayError("Arvan DNS API response is invalid")
    return decoded


def _create_record(token: str, challenge: str) -> str:
    response = _arvan_request(
        token,
        "POST",
        f"/domains/{DOMAIN}/dns-records",
        {
            "type": "txt",
            "name": TARGET_RECORD_NAME,
            "value": {"text": challenge},
            "ttl": TTL,
            "cloud": False,
            "upstream_https": "default",
            "ip_filter_mode": {"count": "single", "geo_filter": "none", "order": "none"},
        },
    )
    data = response.get("data")
    record_id = data.get("id") if isinstance(data, dict) else None
    if not isinstance(record_id, str) or not record_id:
        raise RelayError("Arvan DNS API did not return an immutable TXT record id")
    return record_id


def _delete_record(token: str, record_id: str) -> None:
    if not re.fullmatch(r"[0-9a-f-]{16,80}", record_id):
        raise RelayError("TXT record id is invalid")
    _arvan_request(token, "DELETE", f"/domains/{DOMAIN}/dns-records/{record_id}")


def _upload_verified(client, *, bucket: str, key: str, payload: bytes, metadata: dict[str, str]) -> dict[str, Any]:  # noqa: ANN001
    if not payload or len(payload) > 2 * 1024 * 1024:
        raise RelayError("relay upload payload is outside its bounded size")
    digest = hashlib.sha256(payload).hexdigest()
    response = client.put_object(Bucket=bucket, Key=key, Body=payload, ContentLength=len(payload), ContentType="application/json", Metadata=metadata)
    head = client.head_object(Bucket=bucket, Key=key)
    version_id = str(head.get("VersionId") or response.get("VersionId") or "")
    if not version_id or int(head.get("ContentLength") or -1) != len(payload) or head.get("Metadata") != metadata:
        raise RelayError("Object Storage upload lacks exact versioned metadata")
    remote = client.get_object(Bucket=bucket, Key=key, VersionId=version_id)
    try:
        observed = remote["Body"].read(len(payload) + 1)
    finally:
        close = getattr(remote.get("Body"), "close", None)
        if callable(close):
            close()
    if observed != payload:
        raise RelayError("Object Storage readback differs from relay upload")
    return {"key": key, "version_id": version_id, "sha256": digest, "bytes": len(payload)}


def _presigned(client, operation: str, bucket: str, key: str, method: str, ttl_seconds: int) -> str:  # noqa: ANN001
    if method == "get":
        url = client.generate_presigned_url("get_object", Params={"Bucket": bucket, "Key": key}, ExpiresIn=ttl_seconds)
    elif method == "put":
        url = client.generate_presigned_url("put_object", Params={"Bucket": bucket, "Key": key, "ContentType": "application/json"}, ExpiresIn=ttl_seconds)
    else:  # pragma: no cover - fixed caller surface
        raise RelayError("presigned relay method is invalid")
    return _validate_object_url(url, label=f"{operation} URL")


def provision(args: argparse.Namespace) -> int:
    prefix = _safe_prefix(args.prefix)
    ttl_seconds = int(args.ttl_seconds)
    if not 90 <= ttl_seconds <= MAX_OPERATION_SECONDS:
        raise RelayError("relay URL lifetime must be between 90 and 900 seconds")
    hook = Path(args.hook or __file__).resolve()
    hook_bytes = _safe_regular(hook, label="relay hook", max_bytes=512 * 1024, private=False)
    credentials = _parse_credentials(Path(args.credentials))
    client = _client(credentials)
    bucket = str(args.bucket).strip().lower()
    if not re.fullmatch(r"[a-z0-9][a-z0-9.-]{2,62}", bucket):
        raise RelayError("Object Storage bucket is invalid")
    _require_private_versioned_bucket(client, bucket)
    operation = uuid4().hex
    deadline = int(time.time()) + ttl_seconds
    root = f"{prefix}/{operation}"
    hook_object = _upload_verified(
        client,
        bucket=bucket,
        key=f"{root}/hook.py",
        payload=hook_bytes,
        metadata={"kind": "emergency-ir-acme-hook", "operation": operation},
    )
    request_key = f"{root}/mailbox/request.json"
    response_key = f"{root}/mailbox/response.json"
    operation_descriptor = {
        "schema": SCHEMA,
        "operation_id": operation,
        "domain": DOMAIN,
        "target_fqdn": TARGET_FQDN,
        "deadline_epoch": deadline,
        "request_put_url": _presigned(client, "request", bucket, request_key, "put", ttl_seconds),
        "response_get_url": _presigned(client, "response", bucket, response_key, "get", ttl_seconds),
    }
    descriptor_bytes = _json_bytes(operation_descriptor)
    descriptor_object = _upload_verified(
        client,
        bucket=bucket,
        key=f"{root}/operation.json",
        payload=descriptor_bytes,
        metadata={"kind": "emergency-ir-acme-operation", "operation": operation},
    )
    bootstrap = {
        "schema": SCHEMA,
        "operation_id": operation,
        "deadline_epoch": deadline,
        "hook": {**hook_object, "url": _presigned(client, "hook", bucket, hook_object["key"], "get", ttl_seconds)},
        "descriptor": {**descriptor_object, "url": _presigned(client, "descriptor", bucket, descriptor_object["key"], "get", ttl_seconds)},
    }
    state = {
        "schema": SCHEMA,
        "operation_id": operation,
        "bucket": bucket,
        "request_key": request_key,
        "response_key": response_key,
        "deadline_epoch": deadline,
        "record_id": None,
        "challenge_value": None,
        "last_request_id": None,
        "completed": False,
    }
    _write_private_json(Path(args.bootstrap_output), bootstrap, label="relay bootstrap")
    _write_private_json(Path(args.operation_output), state, label="relay operation state")
    print(json.dumps({"status": "provisioned", "operation_id": operation, "deadline_epoch": deadline, "bucket": bucket, "prefix": root, "hook_sha256": hook_object["sha256"], "descriptor_sha256": descriptor_object["sha256"]}, sort_keys=True))
    return 0


def _get_request(client, bucket: str, key: str) -> dict[str, Any] | None:  # noqa: ANN001
    try:
        result = client.get_object(Bucket=bucket, Key=key)
    except Exception as exc:
        response = getattr(exc, "response", {})
        code = str((response.get("Error") or {}).get("Code") or "") if isinstance(response, dict) else ""
        if code in {"NoSuchKey", "404", "NotFound"}:
            return None
        raise RelayError("unable to read Object Storage relay request") from exc
    try:
        raw = result["Body"].read(MAX_JSON_BYTES + 1)
    finally:
        close = getattr(result.get("Body"), "close", None)
        if callable(close):
            close()
    if not raw or len(raw) > MAX_JSON_BYTES:
        raise RelayError("relay request object is outside its bounded size")
    try:
        value = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RelayError("relay request object is not JSON") from exc
    if not isinstance(value, dict):
        raise RelayError("relay request object is not a JSON object")
    return value


def _put_response(client, state: dict[str, Any], response: dict[str, Any]) -> None:  # noqa: ANN001
    client.put_object(
        Bucket=state["bucket"],
        Key=state["response_key"],
        Body=_json_bytes(response),
        ContentType="application/json",
    )


def serve(args: argparse.Namespace) -> int:
    state_path = Path(args.operation)
    state = _read_json(state_path, label="relay operation state")
    if state.get("schema") != SCHEMA:
        raise RelayError("relay operation state schema is invalid")
    operation = _safe_operation(state.get("operation_id"))
    bucket = str(state.get("bucket") or "")
    request_key = str(state.get("request_key") or "")
    response_key = str(state.get("response_key") or "")
    try:
        deadline = int(state.get("deadline_epoch"))
    except (TypeError, ValueError) as exc:
        raise RelayError("relay operation deadline is invalid") from exc
    if not bucket or not request_key or not response_key or deadline <= int(time.time()):
        raise RelayError("relay operation state is expired or malformed")
    descriptor = {
        "schema": SCHEMA,
        "operation_id": operation,
        "domain": DOMAIN,
        "target_fqdn": TARGET_FQDN,
        "deadline_epoch": deadline,
        "request_put_url": f"https://{OBJECT_STORAGE_HOST}/placeholder?bounded=1",
        "response_get_url": f"https://{OBJECT_STORAGE_HOST}/placeholder?bounded=1",
    }
    _validate_descriptor(descriptor)
    client = _client(_parse_credentials(Path(args.credentials)))
    _require_private_versioned_bucket(client, bucket)
    token = _read_token(Path(args.arvan_token), label="Arvan DNS token")
    poll = max(1, min(int(args.poll_seconds), 10))
    while int(time.time()) < deadline:
        raw = _get_request(client, bucket, request_key)
        if raw is None:
            time.sleep(poll)
            continue
        try:
            request = _validate_request(raw, descriptor)
        except RelayError as exc:
            # A malformed request cannot cause a DNS mutation.  It receives a
            # bounded error only when its operation id is syntactically valid.
            if raw.get("operation_id") == operation and OPERATION_RE.fullmatch(str(raw.get("request_id") or "")):
                _put_response(client, state, {"schema": SCHEMA, "operation_id": operation, "action": str(raw.get("action") or "invalid"), "request_id": str(raw.get("request_id")), "status": "error", "timestamp": _utc_now(), "error": str(exc)[:240]})
            time.sleep(poll)
            continue
        if request["request_id"] == state.get("last_request_id"):
            time.sleep(poll)
            continue
        if request["action"] == "present":
            if state.get("record_id") is not None:
                response = _response(request, status="error", error="a TXT record is already active for this one-shot operation")
            else:
                try:
                    record_id = _create_record(token, request["value"])
                    state.update(record_id=record_id, challenge_value=request["value"], last_request_id=request["request_id"])
                    _write_private_json(state_path, state, label="relay operation state")
                    response = _response(request, status="ok")
                except RelayError as exc:
                    state["last_request_id"] = request["request_id"]
                    _write_private_json(state_path, state, label="relay operation state")
                    response = _response(request, status="error", error=str(exc))
            _put_response(client, state, response)
        else:
            if state.get("record_id") is None or request["value"] != state.get("challenge_value"):
                response = _response(request, status="error", error="cleanup does not match the active one-shot TXT record")
                _put_response(client, state, response)
            else:
                try:
                    _delete_record(token, str(state["record_id"]))
                    state.update(record_id=None, challenge_value=None, last_request_id=request["request_id"], completed=True)
                    _write_private_json(state_path, state, label="relay operation state")
                    _put_response(client, state, _response(request, status="ok"))
                    print(json.dumps({"status": "completed", "operation_id": operation}, sort_keys=True))
                    return 0
                except RelayError as exc:
                    _put_response(client, state, _response(request, status="error", error=str(exc)))
        time.sleep(poll)
    record_id = state.get("record_id")
    if record_id:
        try:
            _delete_record(token, str(record_id))
        except RelayError:
            pass
    state.update(record_id=None, challenge_value=None, completed=False, timed_out=True)
    _write_private_json(state_path, state, label="relay operation state")
    raise RelayError("relay operation timed out; any known TXT record cleanup was attempted")


def hook(args: argparse.Namespace) -> int:
    descriptor = _validate_descriptor(_read_json(Path(args.descriptor), label="WA-IR relay descriptor"))
    action = str(args.action)
    fqdn = str(args.fqdn)
    challenge = str(args.value)
    if action not in {"present", "cleanup"} or fqdn != TARGET_FQDN or not VALUE_RE.fullmatch(challenge):
        raise RelayError("lego hook arguments are outside the exact challenge allowlist")
    request = {
        "schema": SCHEMA,
        "operation_id": descriptor["operation_id"],
        "action": action,
        "fqdn": fqdn,
        "value": challenge,
        "request_id": uuid4().hex,
    }
    _http_json("PUT", descriptor["request_put_url"], payload=request)
    while int(time.time()) < descriptor["deadline_epoch"]:
        response = _http_json("GET", descriptor["response_get_url"], allow_404=True)
        if response is None:
            time.sleep(2)
            continue
        if (
            response.get("schema") == SCHEMA
            and response.get("operation_id") == descriptor["operation_id"]
            and response.get("action") == action
            and response.get("request_id") == request["request_id"]
        ):
            if response.get("status") == "ok":
                print(json.dumps({"status": "acknowledged", "action": action, "operation_id": descriptor["operation_id"]}, sort_keys=True))
                return 0
            raise RelayError(f"controller rejected DNS {action}: {str(response.get('error') or 'unknown error')[:240]}")
        time.sleep(2)
    raise RelayError("relay acknowledgement did not arrive before the short-lived operation expired")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    provision_parser = commands.add_parser("provision", help="publish a one-shot non-secret WA-IR relay hook")
    provision_parser.add_argument("--credentials", required=True)
    provision_parser.add_argument("--bucket", required=True)
    provision_parser.add_argument("--prefix", default="emergency-ir/acme-relay")
    provision_parser.add_argument("--ttl-seconds", default=840, type=int)
    provision_parser.add_argument("--hook")
    provision_parser.add_argument("--bootstrap-output", required=True)
    provision_parser.add_argument("--operation-output", required=True)
    provision_parser.set_defaults(handler=provision)
    serve_parser = commands.add_parser("serve", help="service one bounded Object Storage relay operation")
    serve_parser.add_argument("--credentials", required=True)
    serve_parser.add_argument("--arvan-token", required=True)
    serve_parser.add_argument("--operation", required=True)
    serve_parser.add_argument("--poll-seconds", default=2, type=int)
    serve_parser.set_defaults(handler=serve)
    hook_parser = commands.add_parser("hook", help="lego exec hook, intended for WA-IR")
    hook_parser.add_argument("--descriptor", required=True)
    hook_parser.add_argument("action", choices=("present", "cleanup"))
    hook_parser.add_argument("fqdn")
    hook_parser.add_argument("value")
    hook_parser.set_defaults(handler=hook)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return int(args.handler(args))
    except RelayError as exc:
        print(json.dumps({"status": "error", "error": str(exc)}, sort_keys=True), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
