#!/usr/bin/env python3
"""Provision Writer/Witness controller state and its public human policy.

The issuer passphrase verifier, TOTP seed, recovery material, state, and private
key must never be passed to this utility.  It accepts and installs only the
strict public verifier policy generated by the isolated approval issuer.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import stat
import sys
import tempfile
from typing import Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from core.canonical_json import canonical_json_bytes
from core.human_approval import load_human_approval_policy


PRODUCTION_CONFIG_ROOT = Path("/etc/trading-bot-witness-matrix")
PRODUCTION_CONTROLLER_ROOT = Path("/var/lib/trading-bot-witness-matrix")
PRODUCTION_RUNTIME_ROOT = Path("/run/writer-witness-matrix-controller")
MAX_POLICY_BYTES = 64 * 1024


class ProvisionError(RuntimeError):
    """A fail-closed provisioning validation error."""


def _strict_object(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ProvisionError("human approval policy contains a duplicate key")
        result[key] = value
    return result


@dataclass(frozen=True)
class ProvisionConfig:
    human_approval_policy_file: Path
    config_root: Path = PRODUCTION_CONFIG_ROOT
    controller_root: Path = PRODUCTION_CONTROLLER_ROOT
    runtime_root: Path = PRODUCTION_RUNTIME_ROOT
    owner_uid: int = 0
    owner_gid: int = 0
    test_mode: bool = False


def _write_all(descriptor: int, raw: bytes) -> None:
    offset = 0
    while offset < len(raw):
        written = os.write(descriptor, raw[offset:])
        if written <= 0:
            raise ProvisionError("short write while publishing human approval policy")
        offset += written


def _fsync_directory(path: Path) -> None:
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC | getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open(path, flags)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _validate_root_path(path: Path, *, label: str) -> Path:
    if not path.is_absolute():
        raise ProvisionError(f"{label} must be an absolute path")
    normalized = Path(os.path.normpath(os.fspath(path)))
    if normalized != path:
        raise ProvisionError(f"{label} must not contain traversal components")
    try:
        resolved = path.resolve(strict=False)
    except OSError as exc:
        raise ProvisionError(f"cannot resolve {label}") from exc
    if resolved != path:
        raise ProvisionError(f"{label} must not traverse a symbolic link")
    return path


def _ensure_directory(path: Path, *, uid: int, gid: int) -> None:
    try:
        path.mkdir(mode=0o700)
        created = True
    except FileExistsError:
        created = False
    except OSError as exc:
        raise ProvisionError(f"cannot create controller directory: {path}") from exc
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as exc:
        raise ProvisionError(f"controller path is not a real directory: {path}") from exc
    try:
        metadata = os.fstat(descriptor)
        if not stat.S_ISDIR(metadata.st_mode):
            raise ProvisionError(f"controller path is not a directory: {path}")
        if not created and (metadata.st_uid != uid or metadata.st_gid != gid):
            raise ProvisionError(f"controller directory has an unexpected owner: {path}")
        if created:
            os.fchown(descriptor, uid, gid)
        os.fchmod(descriptor, 0o700)
        os.fsync(descriptor)
        verified = os.fstat(descriptor)
        if (
            verified.st_uid != uid
            or verified.st_gid != gid
            or stat.S_IMODE(verified.st_mode) != 0o700
        ):
            raise ProvisionError(f"controller directory hardening failed: {path}")
    finally:
        os.close(descriptor)
    _fsync_directory(path.parent)


def _read_owner_safe_policy(path: Path, *, uid: int, gid: int) -> bytes:
    flags = os.O_RDONLY | os.O_CLOEXEC | os.O_NONBLOCK | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as exc:
        raise ProvisionError("cannot securely open human approval policy") from exc
    try:
        before = os.fstat(descriptor)
        if (
            not stat.S_ISREG(before.st_mode)
            or before.st_uid != uid
            or before.st_gid != gid
            or stat.S_IMODE(before.st_mode) != 0o600
            or before.st_nlink != 1
            or not 1 <= before.st_size <= MAX_POLICY_BYTES
        ):
            raise ProvisionError(
                "human approval policy must be one owner-controlled mode-0600 regular file"
            )
        raw = b""
        while len(raw) < before.st_size:
            chunk = os.read(descriptor, before.st_size - len(raw))
            if not chunk:
                raise ProvisionError("human approval policy changed during read")
            raw += chunk
        after = os.fstat(descriptor)
        stable = ("st_dev", "st_ino", "st_mode", "st_uid", "st_gid", "st_nlink", "st_size")
        if any(getattr(before, field) != getattr(after, field) for field in stable):
            raise ProvisionError("human approval policy changed during read")
        return raw
    finally:
        os.close(descriptor)


def _assert_existing_target_safe(path: Path, *, uid: int, gid: int) -> None:
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return
    if (
        not stat.S_ISREG(metadata.st_mode)
        or metadata.st_uid != uid
        or metadata.st_gid != gid
        or stat.S_IMODE(metadata.st_mode) != 0o600
        or metadata.st_nlink != 1
    ):
        raise ProvisionError(
            "existing human approval policy must be one owner-controlled mode-0600 regular file"
        )


def _atomic_install(path: Path, raw: bytes, *, uid: int, gid: int) -> None:
    if not raw or len(raw) > MAX_POLICY_BYTES:
        raise ProvisionError("refusing to publish an invalid human approval policy")
    _assert_existing_target_safe(path, uid=uid, gid=gid)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.install-", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        os.fchown(descriptor, uid, gid)
        _write_all(descriptor, raw)
        os.fsync(descriptor)
        os.close(descriptor)
        descriptor = -1
        os.replace(temporary, path)
        _fsync_directory(path.parent)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        if temporary.exists():
            temporary.unlink()
            _fsync_directory(path.parent)
    installed = _read_owner_safe_policy(path, uid=uid, gid=gid)
    if installed != raw:
        raise ProvisionError("installed human approval policy failed read-back attestation")


def _validate_execution_context(config: ProvisionConfig) -> None:
    roots = (
        _validate_root_path(config.config_root, label="config root"),
        _validate_root_path(config.controller_root, label="controller root"),
        _validate_root_path(config.runtime_root, label="runtime root"),
    )
    if len(set(roots)) != 3:
        raise ProvisionError("controller roots must be three distinct paths")
    if config.owner_uid < 0 or config.owner_gid < 0:
        raise ProvisionError("owner uid and gid must be non-negative")
    if config.test_mode:
        if any(
            path in {PRODUCTION_CONFIG_ROOT, PRODUCTION_CONTROLLER_ROOT, PRODUCTION_RUNTIME_ROOT}
            for path in roots
        ):
            raise ProvisionError("test mode must not target a production controller root")
        return
    if os.geteuid() != 0:
        raise ProvisionError("production controller provisioning must run as root")
    if roots != (
        PRODUCTION_CONFIG_ROOT,
        PRODUCTION_CONTROLLER_ROOT,
        PRODUCTION_RUNTIME_ROOT,
    ) or config.owner_uid != 0 or config.owner_gid != 0:
        raise ProvisionError("production roots and ownership cannot be overridden")


def provision(config: ProvisionConfig) -> dict[str, object]:
    _validate_execution_context(config)
    source_raw = _read_owner_safe_policy(
        config.human_approval_policy_file,
        uid=config.owner_uid,
        gid=config.owner_gid,
    )
    try:
        source = json.loads(source_raw, object_pairs_hook=_strict_object)
        policy = load_human_approval_policy(source)
    except Exception as exc:
        raise ProvisionError("human approval policy is invalid") from exc
    canonical = canonical_json_bytes(source) + b"\n"

    for path in (config.config_root, config.controller_root, config.runtime_root):
        if not path.parent.is_dir():
            raise ProvisionError(f"controller root parent does not exist: {path.parent}")
        _ensure_directory(path, uid=config.owner_uid, gid=config.owner_gid)
    for path in (
        config.controller_root / "campaigns",
        config.controller_root / "campaigns" / "consumed-approvals",
        config.controller_root / "campaigns" / "consumed-preflights",
        config.controller_root / "runs",
    ):
        _ensure_directory(path, uid=config.owner_uid, gid=config.owner_gid)

    policy_path = config.config_root / "human-approval-policy.json"
    _atomic_install(policy_path, canonical, uid=config.owner_uid, gid=config.owner_gid)
    return {
        "schema_version": "writer_witness_matrix_controller_provision_v2",
        "human_approval_policy": str(policy_path),
        "human_approval_policy_sha256": hashlib.sha256(canonical_json_bytes(source)).hexdigest(),
        "policy_id": policy.policy_id,
        "operator": policy.operator,
        "issuer_id": policy.issuer_id,
        "key_id": policy.key_id,
        "issuer_secrets_copied": False,
        "directories": [
            str(config.controller_root),
            str(config.controller_root / "campaigns"),
            str(config.controller_root / "campaigns" / "consumed-approvals"),
            str(config.controller_root / "campaigns" / "consumed-preflights"),
            str(config.controller_root / "runs"),
            str(config.runtime_root),
        ],
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--human-approval-policy-file", required=True, type=Path)
    parser.add_argument("--test-mode", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--config-root", type=Path, default=PRODUCTION_CONFIG_ROOT, help=argparse.SUPPRESS)
    parser.add_argument("--controller-root", type=Path, default=PRODUCTION_CONTROLLER_ROOT, help=argparse.SUPPRESS)
    parser.add_argument("--runtime-root", type=Path, default=PRODUCTION_RUNTIME_ROOT, help=argparse.SUPPRESS)
    parser.add_argument("--owner-uid", type=int, default=0, help=argparse.SUPPRESS)
    parser.add_argument("--owner-gid", type=int, default=0, help=argparse.SUPPRESS)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        result = provision(
            ProvisionConfig(
                human_approval_policy_file=args.human_approval_policy_file,
                config_root=args.config_root,
                controller_root=args.controller_root,
                runtime_root=args.runtime_root,
                owner_uid=args.owner_uid,
                owner_gid=args.owner_gid,
                test_mode=args.test_mode,
            )
        )
    except (OSError, ProvisionError) as exc:
        print(f"controller provisioning refused: {exc}", file=sys.stderr)
        return 2
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
