apiVersion: 1

policies:
  - orgId: 1
    receiver: ${GRAFANA_ALERT_DEFAULT_RECEIVER}
    group_by:
      - grafana_folder
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: ${GRAFANA_ALERT_CRITICAL_RECEIVER}
        object_matchers:
          - ["severity", "=", "critical"]
        repeat_interval: 30m
      - receiver: ${GRAFANA_ALERT_WARNING_RECEIVER}
        object_matchers:
          - ["severity", "=", "warning"]
        repeat_interval: 2h
