apiVersion: 1

policies:
  - orgId: 1
    receiver: Trading Bot Local Webhook
    group_by:
      - grafana_folder
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: Trading Bot Local Webhook
        object_matchers:
          - ["severity", "=", "critical"]
        repeat_interval: 30m
      - receiver: Trading Bot Local Webhook
        object_matchers:
          - ["severity", "=", "warning"]
        repeat_interval: 2h

